### PR TITLE
Add comments on HTML injection in index

### PR DESCRIPTION
**Pull request by BrainCrumbz**
So to clarify why it does not contain any reference to bundled scripts nor styles.

### CODE REVIEW

**Comment by Foxandxss** [comment]
This PR is a no for me. We don't need those comments in there and they will remain on production for no good reason.

**Comment by ocombe** [comment]
I agree that we shouldn't add comments to the index, but maybe we could add a note in the readme file ?

**Comment by Foxandxss** [comment]
I can do that.

**Comment by BrainCrumbz** [comment]
that's fine

**Pull request closed without merging**
