### PR TITLE
international support for date formatting

### PR DESCRIPTION
**Pull request by gravity-addiction**

### CODE REVIEW

**Comment by Foxandxss** [comment]
Sorry but we want to keep the starter as simple as possible. This is a nice extra but it is better that the end user do it if needed.

Thank you.

**Comment by gravity-addiction** [comment]
It's really a cross browser compatibility issue. your starter didn't allow me any default date pipes using safari.

**Comment by Foxandxss** [comment]
That is another thing. I will leave it open until I research more.

Ping @ocombe

**Comment by gravity-addiction** [comment]
I have confirmed the problem in both safari 9.0.2 and just now updated to 9.0.3..
EXCEPTION: ReferenceError: Can't find variable: Intl in [
Chrome works just fine with or without Intl module included.

**Comment by ocombe** [comment]
We might want to add this one until this bug is fixed: https://github.com/angular/angular/issues/3333

**Pull request closed without merging**
