### PR TITLE
update codelyzer and dependencies

### PR DESCRIPTION
**Pull request by GaryB432**
I wanted to use some new lint rules from [tslint-microsoft-contrib](https://github.com/Microsoft/tslint-microsoft-contrib) and found our `tslint` was a little out of date.  Trying to update that I found some cascading dependencies which led me to update `codelyzer` and `typescript` itself.  I took codelyzer's suggested rules and adapted them into our `tslint.json`. The src still passes all the rules with one simple change to an access modifier in `app.component`.

No offense taken if I am missing potential problems with this update and you pass on the merge.  But here you go if you want it.

### CODE REVIEW

**Comment by GaryB432** [comment]
well it looks like `typedoc` needs an update too. sorry for the misfire.

**Comment by Foxandxss** [comment]
Pr is nice but I would like:

* tslint to 4.3
* not putting the injection to public
* not new rules in tslint, I will analyze new ones and create a new PR. Exception the ones that are changed (component and directive prefixes & stuff).

**Comment by GaryB432** [comment]
Sounds good

**Comment by GaryB432** [comment]
Oops also wanted to mention that I did understand the principle about binding to private members. That template does seem to me to be a consumer which would only have public access. I'll wait to see how you come down on that new codelyzer rule.

**Comment by GaryB432** [comment]
here's  [bit of discussion](https://groups.google.com/forum/#!msg/angular/D_O_1fqA9WQ/pRNQARRiBgAJ) rationale behind the `templates-use-public` codelyzer rule

**Comment by Foxandxss** [comment]
The rules are nice, but it is better to have a PR focused on one thing, in this case update deps and if you want new rules, create a new PR and we talk :)

**Pull request closed without merging**
