### PR TITLE
add angular2 material project

### PR DESCRIPTION
**Pull request by ShankarSumanth**
Added the angular2 material project and it's dependencies.

### CODE REVIEW

**Comment by Foxandxss** [comment]
This starter is meant to be as simple as possible. 

It is better for the end user to be able to decide what to add than forcing lot of them to remove some dependencies because they don't need it.

**Comment by samfrach** [comment]
@Foxandxss : angular2-material is unfortunately still alpha, most of UI components (like lists) are missing.
but the ng2-translate module is also great...
and many more... but where are they ?

The angular2 echosystem is becoming big and because there were many "ideas" during the alpha, beta and RCx phases, searching on google brings now a lot of pollution ... obsolete components, solutions, and so on ... Angular2 website is incomplete, most of advanced topics are not covered, I discover them in forums, not even in books..  

You have a great starter, you have a not so small community on this project. Would it make sense to extend your starter in a kind of subprojects way in order to include the best of extensions ? We are spending all a lot of time to find the right extensions... this starter, whose core would be as you mentioned the most simple as possible, could be greatly extended.... if it not possible, this could be the "angular2-webpack-andthenwhat" project.  
The idea would be to have a kind of repository of all working and useful components or tools and a hello world on how to start with them and configure them in the starter and of course a status to know if the components are still developped and maintained....
I know, you could tell me, do it yourself :) 

thank you

**Comment by Foxandxss** [comment]
This is an interesting response, so let's go by parts.

>angular2-material is unfortunately still alpha, most of UI components (like lists) are missing.
but the ng2-translate module is also great...
and many more... but where are they ?

I don't follow you here. Where are they? Well, in their respective github and npm packages. If you need any of them at any time, you just need to npm install it using the starter and you are good to go.

You don't really need to add those packages as "default" in the starter, they are just one step away.

>The angular2 echosystem is becoming big and because there were many "ideas" during the alpha, beta and RCx phases, searching on google brings now a lot of pollution ... obsolete components, solutions, and so on ...

My advice here is simply to read the official docs, whether it is Angular docs or the third party docs. They are supposed to have a up to date readme that you can use to be able to use the tool.

> Angular2 website is incomplete, most of advanced topics are not covered, I discover them in forums, not even in books..

Please, send me an email with all your concerns about the website. I am part of the docs team of Angular so that page is my responsibility. Just tell me what do you think it is wrong / missing or what would you like to see there. No need to lie, I am open minded.

>You have a great starter, you have a not so small community on this project. Would it make sense to extend your starter in a kind of subprojects way in order to include the best of extensions ?

Thank you sir. And no, it doesn't make sense. Today there are 5 "good extensions" (I made up that number) but tomorrow you can have 20. The good part is that installing say `ng-bootstrap` is just one step away. You npm install it and you are good to go.

And I hear you with your need of having multiple starters, but they are really really time consuming and there is no great value. Adding third party stuff is really easy.

**Comment by bankrot** [comment]
Is anybody knows how to add custom theme to angular2-webpack + angular2-material

**Comment by kuncevic** [comment]
@bankrot have u already managed to add a theme? I might be looking in to this one on Friday.

**Pull request closed without merging**
