### PR TITLE
Awesome typescript loader and fix sourcemap in test-watch mode

### PR DESCRIPTION
**Pull request by onlyann**
This replaces `ts-loader` with  `awesome-typescript-loader` to speed up incremental changes of typescript files with the [forkchercker](https://github.com/s-panferov/awesome-typescript-loader#forkchecker-boolean-defaultfalse) option.

This also skips code coverage instrumentation in test-watch mode so that it becomes possible to debug unit tests in Chrome with the Typescript files as opposed to the transpiled JavaScript.

### CODE REVIEW

**Comment by Foxandxss** [comment]
I don't dislike the idea of having a-t-l instead of t-l, but last time I tried, I couldn't get the remap-istanbul to work with it. Also I like the idea to be able to debug tests.

That being said, have you tried this PR? I don't like what I see and there are a few errors. There is no `ENV` in karma nor you can import stuff like you did in package.json.

**Comment by Foxandxss** [comment]
webpack config is still broken.

**Comment by onlyann** [comment]
There is indeed an issue with code coverage not using the source map. I think I know how to fix that one.
What error do you have with webpack config ?

**Comment by Foxandxss** [comment]
The line where you import the ForkChecker, it needs to be like the other ones.

**Comment by onlyann** [comment]
Somehow, I have got this working fine on my end. Can it be because I am using Node 6.5 ?

**Comment by Foxandxss** [comment]
That is probably true. In any case, it is always a good idea to use an existent project convention.

**Comment by onlyann** [comment]
Ok. Leave it to me.

**Comment by Foxandxss** [comment]
In any case, the coverage mapped back to TS doesn't work anymore and that is a must.

**Comment by onlyann** [comment]
That should work better now.
The reason I moved remap-istanbul as a NPM post script is because of https://github.com/marcules/karma-remap-istanbul/issues/21.

**Comment by Foxandxss** [comment]
Works for me. We just need to remember adding back the reporter

**Pull request merged**
