### PR TITLE
changes to add remap coverage

### PR DESCRIPTION
**Pull request by abner**
It fixes the issue #104

### CODE REVIEW

**Comment by Foxandxss** [comment]
Oh, awesome. I'll try it later.

**Comment by Foxandxss** [comment]
Works perfect. I tried this in the past but I was having problem.

That being said, I have the feeling that you carried this over from another project and you left some stuff in there. Is everything there needed? Sounds like a lot of code just to use remap.

**Comment by abner** [comment]
yeah. i think i would simplify it just a little bit.

**Comment by abner** [comment]
I think it is good to go now! :)

**Comment by Foxandxss** [comment]
Thanks, I made a little change and I merged it :)

**Comment by abner** [comment]
Awesome! :+1:

**Pull request closed without merging**
